origin: pc-magas/mkdotenv-alpine-staging 
statements:
  - subjects:
      - repo:pc-magas/mkdotenv:** # all refs, workflows, environments
    permissions:
      contents: write
      pull-requests: write
